version: '3'

volumes:
  postgresql:
  redis:
  fms:

networks:
  simple-admin:
    driver: bridge

services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRESQL_DATABASE: 'simple_admin'
      POSTGRESQL_PASSWORD: 'simple-admin.'
    volumes:
      - postgresql:/bitnami/postgresql
    networks:
      simple-admin:
        aliases:
          - postgresql-server
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1000M
        reservations:
          cpus: '0.05'
          memory: 200M

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    networks:
      simple-admin:
        aliases:
          - redis-server
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.05'
          memory: 200M

  core-rpc:
    image: ryanpower/core-rpc-docker:v1.4.3
    container_name: core-rpc
    restart: always
    #    ports:
    #      - '9101:9101'
    networks:
      simple-admin:
        aliases:
          - core-rpc
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.05'
          memory: 200M

  job-rpc:
    image: ryanpower/job-rpc-docker:v1.4.3
    container_name: job-rpc
    restart: always
    #    ports:
    #      - '9105:9105'
    networks:
      simple-admin:
        aliases:
          - job-rpc
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.05'
          memory: 200M

  core-api:
    image: ryanpower/core-api-docker:v1.4.3
    container_name: core-api
    restart: always
    environment:
      I18N_DIR: '/app/etc/'
    #      AUTH_SECRET: 'jS6VKDtsJf3z1n2VKDtsJf3z1n2'
    ports:
      - '9100:9100'
    networks:
      simple-admin:
        aliases:
          - core-api
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.05'
          memory: 200M

  backend-ui:
    image: ryanpower/backend-ui-docker:v1.4.3
    container_name: backend-ui
    restart: always
    ports:
      - '80:80'
    networks:
      simple-admin:
        aliases:
          - backend-ui
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.05'
          memory: 200M

  fms-api:
    image: ryanpower/fms-api-docker:v1.4.3
    container_name: fms-api
    restart: always
    #    environment:
    #      SERVER_URL: 'http://localhost:81'
    #      AUTH_SECRET: 'jS6VKDtsJf3z1n2VKDtsJf3z1n2'
    ports:
      #      - '9102:9102'
      - '81:80'
    volumes:
      - fms:/home/data
    networks:
      simple-admin:
        aliases:
          - fms-api
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.05'
          memory: 200M

  mcms-rpc:
    image: ryanpower/mcms-rpc-docker:v1.4.3
    container_name: mcms-rpc
    restart: always
    #    environment:
    #      EMAIL_ADDR: xxx@gamil.com
    #    ports:
    #      - '9106:9106'
    networks:
      simple-admin:
        aliases:
          - mcms-rpc
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.05'
          memory: 200M