#创建账号
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: simple-admin
  name: find-endpoints

---
#创建角色对应操作
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: discov-endpoints
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get","list","watch"]

---
#给账号绑定角色
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: find-endpoints-discov-endpoints
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: discov-endpoints
subjects:
  - kind: ServiceAccount
    name: find-endpoints
    namespace: simple-admin